<a href="https://colab.research.google.com/github/JairGF05/operaciones_numpy/blob/main/operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **Operación Unique**
Eliminaa los valores repetidos de nuestro array. También se puede saber cuantas veces se repiten dichos datos

In [2]:
arr = np.array([2, 3, 2, 2, 2, 2, 2, 4, 6, 6, 6, 6, 6, 6, 6, 6, 12, 12, 12, 12, 12, 45, 67, 67, 67, 67])
arr

array([ 2,  3,  2,  2,  2,  2,  2,  4,  6,  6,  6,  6,  6,  6,  6,  6, 12,
       12, 12, 12, 12, 45, 67, 67, 67, 67])

In [3]:
#Eliminar valores repetidos
unique = np.unique(arr)
unique

array([ 2,  3,  4,  6, 12, 45, 67])

In [4]:
#Contar el número de ocurrencias
unique, ocurrence = np.unique(arr, return_counts=True)
unique

array([ 2,  3,  4,  6, 12, 45, 67])

In [5]:
ocurrence

array([6, 1, 1, 8, 5, 1, 4])

# **Operaciones con listas**

In [6]:
#lista sando Python
lista = [1, 2]
lista

[1, 2]

In [7]:
#multiplicacion * 2
#Python interpreta que tengo que duplicar8repetir los valores) dos veces lo cual es incorrecto
lista * 2

[1, 2, 1, 2]

# **Operaciones con arreglos de Numpy**

In [8]:
#Creacion de un arreglo de 0 a 10
arr = np.arange(0, 10 )
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#Creación de una copia de arr
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Operaciones con el arreglo de Numpy
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#En el resultado se aprecia que el comportamiento rerspecto a las listas de Python es diferente
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#Ahora se puede sumaar una cantidad a cada uno de los elementos del arreglo
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#Division
1 / arr

<ipython-input-13-679ca7d1b0e2>:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
#Elevar los valores al cuadrado
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
#Suma de arreglos
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#multiplicación de arreglos
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
#Divisiones de arreglos de Numpy
arr / arr2

<ipython-input-17-06325e8d40a3>:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
#Suma de matrices
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
#Multiplicacion de matrices
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [22]:
#Resta de matrices
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
#Producto Punto de una matiz
#Primero obener la transpuesta
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [26]:
#Aplicando matmul
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [27]:
#Otra foprma de obtener el producto punto de una matriz
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])